export const SPACE_ID = process.env.NEXT_PUBLIC_SPACE_ID
export const DELIVERY_ACCESS_TOKEN = process.env.NEXT_PUBLIC_DELIVERY_ACCESS_TOKEN
export const PREVIEW_ACCESS_TOKEN = process.env.NEXT_PUBLIC_PREVIEW_ACCESS_TOKEN
export const NEWRELIC_AGENT_ID = process.env.NEXT_PUBLIC_NEWRELIC_AGENT_ID
export const ENVIRONMENT = process.env.NEXT_PUBLIC_ENVIRONMENT